version: '2.1'

services:
  oclclient:
    image: openmrs/ocl-client:prd
    environment:
      - OCL_API_HOST=${OCL_API_HOST:-https://api.v1.openconceptlab.org}
      - TRADITIONAL_OCL_HOST=${TRADITIONAL_OCL_HOST:-https://v1.openconceptlab.org}
      - ENVIRONMENT=${ENVIRONMENT:-prd}
    ports:
      - 8081:80
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-sSf", "localhost"]
