version: '2.1'

services:
  oclmsp:
    image: openconceptlab/oclmsp:production
    environment:
      - OCL_DOMAIN=${OCL_DOMAIN:-v1.openconceptlab.org}
      - ENVIRONMENT=${ENVIRONMENT:-production}
#    ports:
#      - 8082:80
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost/"]
